[pytest]
testpaths = tests
python_files = *_tests.py test_*.py 
python_classes = Test* 
python_functions = test_* 

markers =
    ui: Запускает все UI автотесты
    courses: Маркировка для тестов, связанных с курсами
    regression: Маркировка для регрессионных тестов